spring.application.name=SGF

spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allow-credentials=true

spring.datasource.url=jdbc:postgresql://localhost:5432/sgf
spring.datasource.username=postgres
spring.datasource.password=punkRock23


server.port=8081